#run with RScript bfc_matrix_plots.r
pdf("bfc_output.pdf", height=20, width=20)
par(mfrow=c(4,4))
image(as.matrix(read.csv("application_atom+xml_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_dif+xml_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_gzip_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_octet-stream_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_pdf_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_rdf+xml_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_rss+xml_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_xhtml+xml_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("application_xml_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("image_gif_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("image_jpeg_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("image_png_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("image_vnd.microsoft.icon_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("text_html_bfc_matrix.csv", header=FALSE)), main="hi")
image(as.matrix(read.csv("text_plain_bfc_matrix.csv", header=FALSE)),main="hi")
dev.off()