library(RSAGA)
#get each file and convert it to a grid
grid1 = grid.to.xyz(as.matrix(read.csv("application_atom+xml_bfc_matrix.csv", header=FALSE)))
grid2 = grid.to.xyz(as.matrix(read.csv("application_dif+xml_bfc_matrix.csv", header=FALSE)))
grid3 = grid.to.xyz(as.matrix(read.csv("application_gzip_bfc_matrix.csv", header=FALSE)))
grid4 = grid.to.xyz(as.matrix(read.csv("application_octet-stream_bfc_matrix.csv", header=FALSE)))
grid5 = grid.to.xyz(as.matrix(read.csv("application_pdf_bfc_matrix.csv", header=FALSE)))
grid6 = grid.to.xyz(as.matrix(read.csv("application_rdf+xml_bfc_matrix.csv", header=FALSE)))
grid7 = grid.to.xyz(as.matrix(read.csv("application_rss+xml_bfc_matrix.csv", header=FALSE)))
grid8 = grid.to.xyz(as.matrix(read.csv("application_xhtml+xml_bfc_matrix.csv", header=FALSE)))
grid9 = grid.to.xyz(as.matrix(read.csv("application_xml_bfc_matrix.csv", header=FALSE)))
grid10 = grid.to.xyz(as.matrix(read.csv("image_gif_bfc_matrix.csv", header=FALSE)))
grid11 = grid.to.xyz(as.matrix(read.csv("image_jpeg_bfc_matrix.csv", header=FALSE)))
grid12 = grid.to.xyz(as.matrix(read.csv("image_png_bfc_matrix.csv", header=FALSE)))
grid13 = grid.to.xyz(as.matrix(read.csv("image_vnd.microsoft.icon_bfc_matrix.csv", header=FALSE)))
grid14 = grid.to.xyz(as.matrix(read.csv("text_html_bfc_matrix.csv" , header=FALSE)))
grid15 = grid.to.xyz(as.matrix(read.csv("text_plain_bfc_matrix.csv", header=FALSE)))

#save each file as a CSV file
write.table(grid1, "3d_application_atom+xml_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid2, "3d_application_dif+xml_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid3, "3d_application_gzip_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid4, "3d_application_octet-stream_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid5, "3d_application_pdf_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid6, "3d_application_rdf+xml_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid7, "3d_application_rss+xml_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid8, "3d_application_xhtml+xml_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid9, "3d_application_xml_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid10, "3d_image_gif_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid11, "3d_image_jpeg_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid12, "3d_image_png_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid13, "3d_image_vnd.microsoft.icon_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid14, "3d_text_html_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)
write.table(grid15, "3d_text_plain_bfc_matrix.tsv", quote=FALSE, sep='\t', row.names=FALSE)